frase = str(input('Digite uma frase: ')).strip().lower()
print('\nAnalisando a frase...')
print('A frase possui {} letras A.'.format(frase.count('a')))
print('A primeira letra A aparece na posição {}.'.format(frase.find('a')+1))
print('A ultima letra A aparece na posição {}.'.format(frase.rfind('a')+1))
